language: node_js
node_js:
  - 13.12.0
script:
  - npm run lint
  - npm run prettier
  - npm run test
  - npm run build
  - npm run type-check
jobs:
  include:
  - stage: Produce Coverage
    script: npm run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
